### ISSUE TITLE
Tab restore order is wild

### ISSUE THREAD

**Issue by themilkman** [sublimehq/sublime_merge#1882]
**Version info**

 - OS: Kubuntu 23.10
 - Build: 2092

**Description**

Restoring closed tabs does not restore them in the inverse order.

**Steps to reproduce**

tab order:
X
A
Y
B
C
D

closing:
A
B
D
C

restore order by SM:
A
C 
B

tab order after restore:
X
Y
A
C
B

**Expected behavior**

Restoring C, D, B, A

(beside the core issue, is is there a way to configure a higher amounts of tabs to restore than only 3 ?)

**Comment by ipmanlk** [comment]
- OS: Manjaro Gnome 23.1.3
- Build: 2092

This issue is happening to me as well.

**Comment by dpjohnst** [comment]
G'day everyone,

Thank you for reporting this issue! I've got a fix for this in the works and will give you an update again once things have progressed.

Cheers,
\- Dylan from Sublime HQ

**Comment by themilkman** [comment]
Thanks for the update, Dylan! 

Will the amount of tabs to restore also get increased?

**Comment by dpjohnst** [comment]
Hi @themilkman,

The maximum amount of tabs to restore is currently set at 128 tabs.
I believe the behavior you're referencing might have been caused by the bug I've just fixed.

Could you confirm if any of the repositories you're seeing this issue with have worktrees enabled?

Cheers,
\- Dylan from Sublime HQ

**Comment by themilkman** [comment]
Hi @dpjohnst, 
I can confirm that at least some of my repos I used for this issue's setup have worktrees enabled.

I just tried it again with a set of repos that don't: 
The tab restore order is still wrong, but I could indeed restore more/all tabs. 
So that seems to be related, yes :-)

Cheers!

**Comment by themilkman** [comment]
Cannot reproduce anymore, seems fixed as of Build 2093 according to changelog.
